const P_IRI_ESWC2019 = 'https://metadata.2019.eswc-conferences.org/rdf';

module.exports = {
	rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
	rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
	xsd: 'http://www.w3.org/2001/XMLSchema#',
	foaf: 'http://xmlns.com/foaf/0.1/',
	earl: 'http://www.w3.org/ns/earl#',
	dct: 'http://purl.org/dc/terms/',
	bibo: 'http://purl.org/ontology/bibo/',
	conference: 'https://w3id.org/scholarlydata/ontology/conference-ontology.owl#',
	role: 'https://w3id.org/scholarlydata/role/',
	eswc2019: P_IRI_ESWC2019+'/ontology/',
	'eswc2019-persons': P_IRI_ESWC2019+'/persons/',
	'eswc2019-affiliations': P_IRI_ESWC2019+'/affiliations/',
	'eswc2019-organizations': P_IRI_ESWC2019+'/organizations/',
	'eswc2019-sites': P_IRI_ESWC2019+'/sites/',
	'eswc2019-proceedings': P_IRI_ESWC2019+'/proceedings/',
	'eswc2019-submissions': P_IRI_ESWC2019+'/submissions/',
	'eswc2019-object': P_IRI_ESWC2019.replace(/\/rdf$/, '/object/'),
	'eswc2019-datatype': P_IRI_ESWC2019+'/datatype/',
	'eswc2019-tuesday': P_IRI_ESWC2019+'/program/tuesday/',
	'eswc2019-wednesday': P_IRI_ESWC2019+'/program/wednesday/',
	'eswc2019-thursday': P_IRI_ESWC2019+'/program/thursday/',
	'hoteli-bernardin': 'https://www.hoteli-bernardin.si/mice/bernardin/congress-halls/',
	owl: 'http://www.w3.org/2002/07/owl#',
	fr: 'http://purl.org/spar/fr/',
	frbr: 'http://purl.org/vocab/frbr/core#',
	bido: 'http://purl.org/spar/bido/',
	cito: 'http://purl.org/spar/cito/',
	fabio: 'http://purl.org/spar/fabio/',
	c4o: 'http://purl.org/spar/c4o/',
	datacite: 'http://purl.org/spar/datacite/',
	literal: 'http://www.essepuntato.it/2010/06/literalreification/',
};
